### PR TITLE
Users/joserady/update docs for marketplace

### PR DESCRIPTION
**Pull request by joserady**

### CODE REVIEW

**Review by cschleiden — COMMENTED** [review]
@joserady Your screenshots contain spelling mistakes, @aaronyzhou has a PR out to fix, can you regenerate?

**Comment by joserady** [comment]
@cschleiden which mistakes so I can fix them?

**Comment by joserady** [comment]
@cschleiden @aaronyzhou it's actually what's defined in the manifest correct? "seperated" instead of "separated"? If that's the case, @aaronyzhou make sure you also fix these given that you're making changes to the manifest already 👍

**Comment by cschleiden** [comment]
@joserady Yep, that's what I meant :)

**Pull request merged**
